spring.application.name=busPassSys
spring.datasource.url=jdbc:mysql://root:oJyKLAPSsHYvnqWvbNahrNTSMiXuQpLk@maglev.proxy.rlwy.net:34613/railway
spring.datasource.username=root
spring.datasource.password=oJyKLAPSsHYvnqWvbNahrNTSMiXuQpLk
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true