spring.application.name=busPassSys
SPRING_DATASOURCE_URL=jdbc:mysql://buspassdb_snakedirty:b44681c934e1e7afd154aeeab4a1d0b128c0366b@uzelwb.h.filess.io:3307/buspassdb_snakedirty
SPRING_DATASOURCE_USERNAME=uzelwb.h.filess.io
SPRING_DATASOURCE_PASSWORD=b44681c934e1e7afd154aeeab4a1d0b128c0366b
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
